language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-5"]
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.9"]
          # Install GCC 5 to ensure the experimental/filesystem headers are
          # available
          packages: ["g++-5", "clang-3.9"]
      env: COMPILER=clang++-3.9

script:
  - make CXX=$COMPILER
  - make CXX=$COMPILER test
